[project]
name = "pyconjp2025"
version = "0.1.0"
description = "Demo code for the PyConJP 2025 talk: 'Beyond Multiprocessing: A Real-World ML Workload Speedup with Python 3.13+ Free-Threading'"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
